// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: souD5h88MhENvTHMTJd8eE
// Component: i-nPMUQB3KRp
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import GraphicIcon from "../../GraphicIcon"; // plasmic-import: e2aIHUlliT40/component
import Linky from "../../Linky"; // plasmic-import: R0_cM2qssTE/component
import ButtonLink from "../../ButtonLink"; // plasmic-import: WEYjixTZW6s/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: KSAzOQ4LXGzQ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_nextjs_ableaura_com.module.css"; // plasmic-import: souD5h88MhENvTHMTJd8eE/projectcss
import * as sty from "./PlasmicSmallValuePropCard.module.css"; // plasmic-import: i-nPMUQB3KRp/css

import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: qXkXmSCGXsaH/icon
import Icon31Icon from "./icons/PlasmicIcon__Icon31"; // plasmic-import: I09jQLSUv79P/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 0UGn88PbJe7i/icon

export type PlasmicSmallValuePropCard__VariantMembers = {
  ltr: "ltr";
  vertical: "vertical";
  rightImage: "rightImage";
  showcaseIsVideo: "showcaseIsVideo";
  reverse: "reverse";
  extraPadding: "extraPadding";
};

export type PlasmicSmallValuePropCard__VariantsArgs = {
  ltr?: SingleBooleanChoiceArg<"ltr">;
  vertical?: SingleBooleanChoiceArg<"vertical">;
  rightImage?: SingleBooleanChoiceArg<"rightImage">;
  showcaseIsVideo?: SingleBooleanChoiceArg<"showcaseIsVideo">;
  reverse?: SingleBooleanChoiceArg<"reverse">;
  extraPadding?: SingleBooleanChoiceArg<"extraPadding">;
};

type VariantPropType = keyof PlasmicSmallValuePropCard__VariantsArgs;
export const PlasmicSmallValuePropCard__VariantProps =
  new Array<VariantPropType>(
    "ltr",
    "vertical",
    "rightImage",
    "showcaseIsVideo",
    "reverse",
    "extraPadding"
  );

export type PlasmicSmallValuePropCard__ArgsType = {
  icon?: React.ReactNode;
  actionButton?: React.ReactNode;
  description?: React.ReactNode;
  followupLink?: React.ReactNode;
  showcaseImage?: React.ReactNode;
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicSmallValuePropCard__ArgsType;
export const PlasmicSmallValuePropCard__ArgProps = new Array<ArgPropType>(
  "icon",
  "actionButton",
  "description",
  "followupLink",
  "showcaseImage",
  "children"
);

export type PlasmicSmallValuePropCard__OverridesType = {
  root?: p.Flex<"div">;
  videoHover?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultSmallValuePropCardProps {
  icon?: React.ReactNode;
  actionButton?: React.ReactNode;
  description?: React.ReactNode;
  followupLink?: React.ReactNode;
  showcaseImage?: React.ReactNode;
  children?: React.ReactNode;
  ltr?: SingleBooleanChoiceArg<"ltr">;
  vertical?: SingleBooleanChoiceArg<"vertical">;
  rightImage?: SingleBooleanChoiceArg<"rightImage">;
  showcaseIsVideo?: SingleBooleanChoiceArg<"showcaseIsVideo">;
  reverse?: SingleBooleanChoiceArg<"reverse">;
  extraPadding?: SingleBooleanChoiceArg<"extraPadding">;
  className?: string;
}

function PlasmicSmallValuePropCard__RenderFunc(props: {
  variants: PlasmicSmallValuePropCard__VariantsArgs;
  args: PlasmicSmallValuePropCard__ArgsType;
  overrides: PlasmicSmallValuePropCard__OverridesType;
  dataFetches?: PlasmicSmallValuePropCard__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__ltr]: hasVariant(variants, "ltr", "ltr"),
        [sty.root__ltr_rightImage]:
          hasVariant(variants, "ltr", "ltr") &&
          hasVariant(variants, "rightImage", "rightImage"),
        [sty.root__reverse]: hasVariant(variants, "reverse", "reverse"),
        [sty.root__rightImage]: hasVariant(
          variants,
          "rightImage",
          "rightImage"
        ),
        [sty.root__showcaseIsVideo]: hasVariant(
          variants,
          "showcaseIsVideo",
          "showcaseIsVideo"
        ),
        [sty.root__vertical]: hasVariant(variants, "vertical", "vertical")
      })}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox___8PJaq, {
          [sty.freeBox__extraPadding___8PJaQxkCA]: hasVariant(
            variants,
            "extraPadding",
            "extraPadding"
          ),
          [sty.freeBox__ltr___8PJaQa8YEs]: hasVariant(variants, "ltr", "ltr"),
          [sty.freeBox__rightImage___8PJaqzOqbR]: hasVariant(
            variants,
            "rightImage",
            "rightImage"
          ),
          [sty.freeBox__rightImage_ltr___8PJaqzOqbRA8YEs]:
            hasVariant(variants, "rightImage", "rightImage") &&
            hasVariant(variants, "ltr", "ltr"),
          [sty.freeBox__vertical___8PJaqAhk9V]: hasVariant(
            variants,
            "vertical",
            "vertical"
          )
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <GraphicIcon
              className={classNames("__wab_instance", sty.graphicIcon__uFu5I)}
            >
              <Icon6Icon
                className={classNames(defaultcss.all, sty.svg__eXmuY)}
                role={"img"}
              />
            </GraphicIcon>
          ),

          value: args.icon
        })}

        <div
          className={classNames(defaultcss.all, sty.freeBox___7VfEn, {
            [sty.freeBox__ltr___7VfEna8YEs]: hasVariant(variants, "ltr", "ltr"),
            [sty.freeBox__rightImage___7VfEnZOqbR]: hasVariant(
              variants,
              "rightImage",
              "rightImage"
            ),
            [sty.freeBox__vertical___7VfEnAhk9V]: hasVariant(
              variants,
              "vertical",
              "vertical"
            )
          })}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.freeBox__hkJl5, {
              [sty.freeBox__rightImage__hkJl5ZOqbR]: hasVariant(
                variants,
                "rightImage",
                "rightImage"
              ),
              [sty.freeBox__vertical__hkJl5Ahk9V]: hasVariant(
                variants,
                "vertical",
                "vertical"
              )
            })}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__gxHNv, {
                [sty.freeBox__ltr__gxHNva8YEs]: hasVariant(
                  variants,
                  "ltr",
                  "ltr"
                ),
                [sty.freeBox__rightImage__gxHNvZOqbR]: hasVariant(
                  variants,
                  "rightImage",
                  "rightImage"
                ),
                [sty.freeBox__rightImage_ltr__gxHNvZOqbRA8YEs]:
                  hasVariant(variants, "rightImage", "rightImage") &&
                  hasVariant(variants, "ltr", "ltr"),
                [sty.freeBox__vertical__gxHNvAhk9V]: hasVariant(
                  variants,
                  "vertical",
                  "vertical"
                )
              })}
            >
              <div className={classNames(defaultcss.all, sty.freeBox__j2BpA)}>
                <div className={classNames(defaultcss.all, sty.freeBox__wgxR6)}>
                  {p.renderPlasmicSlot({
                    defaultContents: "This is the header.",
                    value: args.children,
                    className: classNames(sty.slotTargetChildren)
                  })}
                </div>
              </div>

              <div
                className={classNames(defaultcss.all, sty.freeBox___7NTg7, {
                  [sty.freeBox__ltr___7NTg7A8YEs]: hasVariant(
                    variants,
                    "ltr",
                    "ltr"
                  ),
                  [sty.freeBox__rightImage___7NTg7ZOqbR]: hasVariant(
                    variants,
                    "rightImage",
                    "rightImage"
                  )
                })}
              >
                {p.renderPlasmicSlot({
                  defaultContents:
                    "Run with one of our templates, or start from scratch by drawing boxes and wireframes.",
                  value: args.description
                })}
              </div>

              {p.renderPlasmicSlot({
                defaultContents: (
                  <Linky
                    className={classNames("__wab_instance", sty.linky__wTkOn)}
                    link={
                      "https://studio.plasmic.app/?starters=general,site-builder" as const
                    }
                    style={["noPadding"]}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__x6Vgt
                      )}
                    >
                      {"Browse starter projects ->"}
                    </div>
                  </Linky>
                ),

                value: args.followupLink
              })}
            </p.Stack>
          </p.Stack>
        </div>
      </p.Stack>

      {(hasVariant(variants, "ltr", "ltr") ? true : false) ? (
        <div
          className={classNames(defaultcss.all, sty.freeBox__xnPns, {
            [sty.freeBox__ltr__xnPnsa8YEs]: hasVariant(variants, "ltr", "ltr"),
            [sty.freeBox__rightImage__xnPnsZOqbR]: hasVariant(
              variants,
              "rightImage",
              "rightImage"
            ),
            [sty.freeBox__showcaseIsVideo__xnPns4AnEc]: hasVariant(
              variants,
              "showcaseIsVideo",
              "showcaseIsVideo"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__cdTa4)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                src={{
                  src: "/plasmic/nextjs_ableaura_com/images/image16.png",
                  fullWidth: 928,
                  fullHeight: 594,
                  aspectRatio: undefined
                }}
              />
            ),

            value: args.showcaseImage
          })}

          {(
            hasVariant(variants, "showcaseIsVideo", "showcaseIsVideo")
              ? true
              : false
          ) ? (
            <div
              data-plasmic-name={"videoHover"}
              data-plasmic-override={overrides.videoHover}
              className={classNames(defaultcss.all, sty.videoHover, {
                [sty.videoHover__showcaseIsVideo]: hasVariant(
                  variants,
                  "showcaseIsVideo",
                  "showcaseIsVideo"
                )
              })}
            >
              {(
                hasVariant(variants, "showcaseIsVideo", "showcaseIsVideo")
                  ? true
                  : false
              ) ? (
                <Icon31Icon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(defaultcss.all, sty.svg, {
                    [sty.svg__showcaseIsVideo]: hasVariant(
                      variants,
                      "showcaseIsVideo",
                      "showcaseIsVideo"
                    )
                  })}
                  role={"img"}
                />
              ) : null}
            </div>
          ) : null}
        </div>
      ) : null}
      {p.renderPlasmicSlot({
        defaultContents: (
          <ButtonLink
            className={classNames("__wab_instance", sty.buttonLink__kJzC)}
          />
        ),

        value: args.actionButton
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "videoHover", "svg"],
  videoHover: ["videoHover", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  videoHover: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSmallValuePropCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSmallValuePropCard__VariantsArgs;
    args?: PlasmicSmallValuePropCard__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicSmallValuePropCard__Fetches;
  } & Omit<PlasmicSmallValuePropCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSmallValuePropCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSmallValuePropCard__ArgProps,
      internalVariantPropNames: PlasmicSmallValuePropCard__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicSmallValuePropCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSmallValuePropCard";
  } else {
    func.displayName = `PlasmicSmallValuePropCard.${nodeName}`;
  }
  return func;
}

export const PlasmicSmallValuePropCard = Object.assign(
  // Top-level PlasmicSmallValuePropCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    videoHover: makeNodeComponent("videoHover"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicSmallValuePropCard
    internalVariantProps: PlasmicSmallValuePropCard__VariantProps,
    internalArgProps: PlasmicSmallValuePropCard__ArgProps
  }
);

export default PlasmicSmallValuePropCard;
/* prettier-ignore-end */
