// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: souD5h88MhENvTHMTJd8eE
// Component: MOxc4yW_hfJ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: HOOkYFb7WGkG/component
import Divider from "../../Divider"; // plasmic-import: 5YxrxfKmRHtf/component
import Logo from "../../Logo"; // plasmic-import: raVuHJwR1XD/component
import Linky from "../../Linky"; // plasmic-import: R0_cM2qssTE/component

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: K8kdSftIudYz/globalVariant
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: KSAzOQ4LXGzQ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_nextjs_ableaura_com.module.css"; // plasmic-import: souD5h88MhENvTHMTJd8eE/projectcss
import * as sty from "./PlasmicFooter.module.css"; // plasmic-import: MOxc4yW_hfJ/css

export type PlasmicFooter__VariantMembers = {};

export type PlasmicFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooter__VariantsArgs;
export const PlasmicFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicFooter__ArgsType = {};
type ArgPropType = keyof PlasmicFooter__ArgsType;
export const PlasmicFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicFooter__OverridesType = {
  root?: p.Flex<"section">;
  container?: p.Flex<"div">;
  subscribeForm?: p.Flex<"form">;
  subscribeInput?: p.Flex<typeof TextInput>;
  subscribeButton?: p.Flex<"button">;
  divider?: p.Flex<typeof Divider>;
  logo?: p.Flex<typeof Logo>;
};

export interface DefaultFooterProps {
  className?: string;
}

function PlasmicFooter__RenderFunc(props: {
  variants: PlasmicFooter__VariantsArgs;
  args: PlasmicFooter__ArgsType;
  overrides: PlasmicFooter__OverridesType;
  dataFetches?: PlasmicFooter__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    theme: useTheme(),
    screen: useScreenVariants()
  });

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__global_theme_dark]: hasVariant(
          globalVariants,
          "theme",
          "dark"
        )
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"container"}
        data-plasmic-override={overrides.container}
        hasGap={true}
        className={classNames(defaultcss.all, sty.container)}
      >
        {false ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.freeBox__rVeF)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__wTWkR)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__e2VV
                )}
              >
                {"Subscribe for updates"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__rVeU
                )}
              >
                {"Announcements of our latest features and news."}
              </div>
            </p.Stack>

            <p.Stack
              as={"form"}
              data-plasmic-name={"subscribeForm"}
              data-plasmic-override={overrides.subscribeForm}
              hasGap={true}
              className={classNames(defaultcss.all, sty.subscribeForm)}
            >
              <TextInput
                data-plasmic-name={"subscribeInput"}
                data-plasmic-override={overrides.subscribeInput}
                className={classNames("__wab_instance", sty.subscribeInput)}
              />

              <button
                data-plasmic-name={"subscribeButton"}
                data-plasmic-override={overrides.subscribeButton}
                className={classNames(
                  defaultcss.button,
                  defaultcss.__wab_text,
                  sty.subscribeButton
                )}
              >
                {"Subscribe"}
              </button>
            </p.Stack>
          </p.Stack>
        ) : null}
        {true ? (
          <Divider
            data-plasmic-name={"divider"}
            data-plasmic-override={overrides.divider}
            className={classNames("__wab_instance", sty.divider)}
          />
        ) : null}

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.freeBox__arWx9)}
        >
          {(
            hasVariant(globalVariants, "screen", "mobilePortrait")
              ? false
              : true
          ) ? (
            <Logo
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames("__wab_instance", sty.logo)}
              type={"footer" as const}
            />
          ) : null}

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.freeBox__csw3A, {
              [sty.freeBox__global_theme_altHeadlineFont__csw3AZbUeX]:
                hasVariant(globalVariants, "theme", "altHeadlineFont")
            })}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__xdlWq)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__kFlS7, {
                  [sty.freeBox__global_theme_dark__kFlS7UgT9R]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
              >
                {false ? (
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__fdrw)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__hUoxs,
                        {
                          [sty.text__global_theme_dark__hUoxsUgT9R]: hasVariant(
                            globalVariants,
                            "theme",
                            "dark"
                          )
                        }
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobilePortrait")
                        ? "Product"
                        : "Product"}
                    </div>

                    <Linky
                      className={classNames(
                        "__wab_instance",
                        sty.linky__lezrL,
                        {
                          [sty.linky__global_theme_dark__lezrLUgT9R]:
                            hasVariant(globalVariants, "theme", "dark")
                        }
                      )}
                      leftAligned={"leftAligned" as const}
                      link={"/features" as const}
                      style={[]}
                    >
                      {"Features"}
                    </Linky>

                    <Linky
                      className={classNames("__wab_instance", sty.linky__xlcCq)}
                      leftAligned={"leftAligned" as const}
                      link={"/pricing/" as const}
                      style={[]}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__aOmNu
                        )}
                      >
                        {"Pricing"}
                      </div>
                    </Linky>
                  </div>
                ) : null}

                <div className={classNames(defaultcss.all, sty.freeBox__f104P)}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ogMaw,
                      {
                        [sty.text__global_theme_dark__ogMawUgT9R]: hasVariant(
                          globalVariants,
                          "theme",
                          "dark"
                        )
                      }
                    )}
                  >
                    {"Community"}
                  </div>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__fevrw)}
                    leftAligned={"leftAligned" as const}
                    link={"https://twitter.com/plasmicapp" as const}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__bcqvq
                      )}
                    >
                      {"Twitter"}
                    </div>
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__g4Yn, {
                      [sty.linky__global_theme_dark__g4YnUgT9R]: hasVariant(
                        globalVariants,
                        "theme",
                        "dark"
                      )
                    })}
                    leftAligned={"leftAligned" as const}
                    link={"https://plasmic.app/slack" as const}
                  >
                    {"Slack"}
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__jpi3F)}
                    leftAligned={"leftAligned" as const}
                    link={"https://medium.com/plasmic-app" as const}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___5SE9M
                      )}
                    >
                      {"Blog"}
                    </div>
                  </Linky>
                </div>
              </p.Stack>

              {false ? (
                <div
                  className={classNames(defaultcss.all, sty.freeBox___3Hi1B, {
                    [sty.freeBox__global_theme_dark___3Hi1BUgT9R]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  })}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__yo2Dm,
                      {
                        [sty.text__global_theme_dark__yo2DmUgT9R]: hasVariant(
                          globalVariants,
                          "theme",
                          "dark"
                        )
                      }
                    )}
                  >
                    {"Use Cases"}
                  </div>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__lf5X)}
                    link={"/cms/" as const}
                  >
                    {"Visual CMS"}
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__cofrP)}
                    link={"/site-builder/" as const}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__vrh98
                      )}
                    >
                      {"Website Builder"}
                    </div>
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky___7Zf3M, {
                      [sty.linky__global_theme_dark___7Zf3MUgT9R]: hasVariant(
                        globalVariants,
                        "theme",
                        "dark"
                      )
                    })}
                    link={"/design-systems/" as const}
                  >
                    {"Design Systems"}
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__rKqiZ)}
                    link={"/prototyping/" as const}
                  >
                    {"Prototyping"}
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__cgAs, {
                      [sty.linky__global_theme_dark__cgAsUgT9R]: hasVariant(
                        globalVariants,
                        "theme",
                        "dark"
                      )
                    })}
                    link={"/ui-builder/" as const}
                  >
                    {"UI Builder"}
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__ncl2I, {
                      [sty.linky__global_theme_dark__ncl2IUgT9R]: hasVariant(
                        globalVariants,
                        "theme",
                        "dark"
                      )
                    })}
                    link={"/design-to-code/" as const}
                  >
                    {"Design-to-code"}
                  </Linky>
                </div>
              ) : null}
              {false ? (
                <div
                  className={classNames(defaultcss.all, sty.freeBox___0QtTm, {
                    [sty.freeBox__global_theme_dark___0QtTmUgT9R]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  })}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__fj8Qg,
                      {
                        [sty.text__global_theme_dark__fj8QgUgT9R]: hasVariant(
                          globalVariants,
                          "theme",
                          "dark"
                        )
                      }
                    )}
                  >
                    {"Solutions"}
                  </div>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__hvlIb, {
                      [sty.linky__global_theme_dark__hvlIbUgT9R]: hasVariant(
                        globalVariants,
                        "theme",
                        "dark"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__y6Mro
                      )}
                    >
                      {"Developers"}
                    </div>
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__ipi1E)}
                  >
                    {"Designers"}
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__fzqQk)}
                  >
                    {"Marketing"}
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky___4VUlW)}
                  >
                    {"Enterprise"}
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__lFl9A)}
                  >
                    {"Ecommerce"}
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__nuLj5)}
                  >
                    {"Agencies"}
                  </Linky>
                </div>
              ) : null}

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__yFqW, {
                  [sty.freeBox__global_theme_dark__yFqWUgT9R]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
              >
                {false ? (
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__msuN)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__bes1R,
                        {
                          [sty.text__global_theme_dark__bes1RUgT9R]: hasVariant(
                            globalVariants,
                            "theme",
                            "dark"
                          )
                        }
                      )}
                    >
                      {"Company"}
                    </div>

                    {false ? (
                      <Linky
                        className={classNames(
                          "__wab_instance",
                          sty.linky__raoqy,
                          {
                            [sty.linky__global_theme_dark__raoqyUgT9R]:
                              hasVariant(globalVariants, "theme", "dark")
                          }
                        )}
                        link={"/about/" as const}
                      >
                        {"About"}
                      </Linky>
                    ) : null}

                    <Linky
                      className={classNames(
                        "__wab_instance",
                        sty.linky___7Ddc5
                      )}
                      leftAligned={"leftAligned" as const}
                      link={"/careers/" as const}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__gCNvw
                        )}
                      >
                        {"Careers"}
                      </div>
                    </Linky>
                  </div>
                ) : null}

                <div className={classNames(defaultcss.all, sty.freeBox__lOgM)}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__iwsOn,
                      {
                        [sty.text__global_theme_dark__iwsOnUgT9R]: hasVariant(
                          globalVariants,
                          "theme",
                          "dark"
                        )
                      }
                    )}
                  >
                    {"Resources"}
                  </div>

                  <Linky
                    className={classNames("__wab_instance", sty.linky___7VkMi)}
                    leftAligned={"leftAligned" as const}
                    link={"/learn/" as const}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__sCmne
                      )}
                    >
                      {"Learn"}
                    </div>
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__upIDd)}
                    leftAligned={"leftAligned" as const}
                    link={"/casestudies/" as const}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___0AwLz
                      )}
                    >
                      {"Case Studies"}
                    </div>
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__ries5, {
                      [sty.linky__global_theme_dark__ries5UgT9R]: hasVariant(
                        globalVariants,
                        "theme",
                        "dark"
                      )
                    })}
                    leftAligned={"leftAligned" as const}
                    link={"https://github.com/plasmicapp/plasmic" as const}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__touOk,
                        {
                          [sty.text__global_theme_dark__touOkUgT9R]: hasVariant(
                            globalVariants,
                            "theme",
                            "dark"
                          )
                        }
                      )}
                    >
                      {"Github"}
                    </div>
                  </Linky>

                  <Linky
                    className={classNames("__wab_instance", sty.linky__eomjp)}
                    leftAligned={"leftAligned" as const}
                    link={"/about" as const}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__wzznf
                      )}
                    >
                      {"About"}
                    </div>
                  </Linky>
                </div>
              </p.Stack>
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.freeBox__yl1Sw)}>
              {(
                hasVariant(globalVariants, "theme", "altHeadlineFont")
                  ? false
                  : true
              ) ? (
                <Linky
                  className={classNames("__wab_instance")}
                  link={
                    "https://studio.plasmic.app/projects/kjuFFTSZb8fanzCHT2C1jz" as const
                  }
                  style={["small", "solidCyan"]}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hnX4F,
                      {
                        [sty.text__global_theme_altHeadlineFont__hnX4FZbUeX]:
                          hasVariant(globalVariants, "theme", "altHeadlineFont")
                      }
                    )}
                  >
                    {hasVariant(globalVariants, "theme", "altHeadlineFont") ? (
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                      >
                        <React.Fragment>{"Built "}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontStyle: "italic" }}
                        >
                          {"in"}
                        </span>
                        <React.Fragment>
                          {" Plasmic. View this project ->"}
                        </React.Fragment>
                      </span>
                    ) : (
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                      >
                        <React.Fragment>{"Built "}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontStyle: "italic" }}
                        >
                          {"in"}
                        </span>
                        <React.Fragment>
                          {" Plasmic. View this project ->"}
                        </React.Fragment>
                      </span>
                    )}
                  </div>
                </Linky>
              ) : null}

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__wj9Zn,
                  {
                    [sty.text__global_theme_dark__wj9ZnUgT9R]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  }
                )}
              >
                {"Copyright © 2021 Plasmic, Inc.\nAll rights reserved."}
              </div>

              <div className={classNames(defaultcss.all, sty.freeBox___6Gkyf)}>
                <Linky link={"/privacy/" as const}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vQa7B
                    )}
                  >
                    {"Privacy Policy"}
                  </div>
                </Linky>

                <Linky link={"/tos/" as const}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__uFsQj
                    )}
                  >
                    {"Terms and Conditions"}
                  </div>
                </Linky>
              </div>
            </div>
          </p.Stack>
        </p.Stack>
      </p.Stack>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "container",
    "subscribeForm",
    "subscribeInput",
    "subscribeButton",
    "divider",
    "logo"
  ],
  container: [
    "container",
    "subscribeForm",
    "subscribeInput",
    "subscribeButton",
    "divider",
    "logo"
  ],
  subscribeForm: ["subscribeForm", "subscribeInput", "subscribeButton"],
  subscribeInput: ["subscribeInput"],
  subscribeButton: ["subscribeButton"],
  divider: ["divider"],
  logo: ["logo"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
  container: "div";
  subscribeForm: "form";
  subscribeInput: typeof TextInput;
  subscribeButton: "button";
  divider: typeof Divider;
  logo: typeof Logo;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooter__VariantsArgs;
    args?: PlasmicFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicFooter__Fetches;
  } & Omit<PlasmicFooter__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    container: makeNodeComponent("container"),
    subscribeForm: makeNodeComponent("subscribeForm"),
    subscribeInput: makeNodeComponent("subscribeInput"),
    subscribeButton: makeNodeComponent("subscribeButton"),
    divider: makeNodeComponent("divider"),
    logo: makeNodeComponent("logo"),

    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
