// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: souD5h88MhENvTHMTJd8eE
// Component: 8tjLq0amNeeI
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: gm5-8uP8UsM/component
import PageHero from "../../PageHero"; // plasmic-import: vbMgnF8jjWCL/component
import GraphicIcon from "../../GraphicIcon"; // plasmic-import: e2aIHUlliT40/component
import ValuePropSection from "../../ValuePropSection"; // plasmic-import: 3bwHcXHAsuR/component
import ButtonLink from "../../ButtonLink"; // plasmic-import: WEYjixTZW6s/component
import BottomCtaSection from "../../BottomCtaSection"; // plasmic-import: -1wDuXI1QPgi/component
import Footer from "../../Footer"; // plasmic-import: MOxc4yW_hfJ/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_nextjs_ableaura_com.module.css"; // plasmic-import: souD5h88MhENvTHMTJd8eE/projectcss
import * as sty from "./PlasmicPagePrototyping.module.css"; // plasmic-import: 8tjLq0amNeeI/css

import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: hBHHolMTg55Z/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: qXkXmSCGXsaH/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 0UGn88PbJe7i/icon
import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: 8m1F-mZpTDnT/icon
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: F8u130ZEqhi0/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: Qa2ocDt62Kvq/icon

export type PlasmicPagePrototyping__VariantMembers = {};

export type PlasmicPagePrototyping__VariantsArgs = {};
type VariantPropType = keyof PlasmicPagePrototyping__VariantsArgs;
export const PlasmicPagePrototyping__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPagePrototyping__ArgsType = {};
type ArgPropType = keyof PlasmicPagePrototyping__ArgsType;
export const PlasmicPagePrototyping__ArgProps = new Array<ArgPropType>();

export type PlasmicPagePrototyping__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  pageHero?: p.Flex<typeof PageHero>;
  bottomCtaSection?: p.Flex<typeof BottomCtaSection>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultPagePrototypingProps {
  className?: string;
}

function PlasmicPagePrototyping__RenderFunc(props: {
  variants: PlasmicPagePrototyping__VariantsArgs;
  args: PlasmicPagePrototyping__ArgsType;
  overrides: PlasmicPagePrototyping__OverridesType;
  dataFetches?: PlasmicPagePrototyping__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Header
        data-plasmic-name={"header"}
        data-plasmic-override={overrides.header}
        className={classNames("__wab_instance", sty.header)}
      />

      <PageHero
        data-plasmic-name={"pageHero"}
        data-plasmic-override={overrides.pageHero}
        className={classNames("__wab_instance", sty.pageHero)}
        slot={"Prototyping that's 1 step away from production."}
        slot2={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon__giFwm)}
            colors={"purple" as const}
          >
            <Icon14Icon
              className={classNames(defaultcss.all, sty.svg__rmfhM)}
              role={"img"}
            />
          </GraphicIcon>
        }
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.text__nQ7Tg
          )}
        >
          {"Prototyping"}
        </div>
      </PageHero>

      <ValuePropSection
        backgroundColor={"coral" as const}
        backgroundImage={
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__iknVb)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"none" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            src={{
              src: "/plasmic/nextjs_ableaura_com/images/image6.svg",
              fullWidth: 300,
              fullHeight: 95,
              aspectRatio: 3.150655
            }}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection__pogIk)}
        description={
          "Rapidly design your user interface in the final medium. Stop guessing your flex-basis, or manually dancing around a cross-browser flex-gap. "
        }
        header={"full control"}
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon___4BbaK)}
          >
            <Icon6Icon
              className={classNames(defaultcss.all, sty.svg__p0EYl)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.text___8Duce
            )}
          >
            {"Test your ideas quickly"}
          </div>
        }
      />

      <ValuePropSection
        backgroundColor={"green" as const}
        backgroundImage={
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__gGk6A)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"none" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            src={{
              src: "/plasmic/nextjs_ableaura_com/images/image7.svg",
              fullWidth: 300,
              fullHeight: 145,
              aspectRatio: 2.068966
            }}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection___1PBLq)}
        description={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.text__lzKsu
            )}
          >
            {
              "Don't limit yourself to a throwaway prototype. Plasmic generates maintainable production-ready presentational components so you can ship faster."
            }
          </div>
        }
        header={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.text__abP3G
            )}
          >
            {"#nocode"}
          </div>
        }
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon__iJfbT)}
            colors={"green" as const}
          >
            <Icon6Icon
              className={classNames(defaultcss.all, sty.svg__vb2Zi)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={"Automatically get ready-to-use React components"}
      />

      <ValuePropSection
        backgroundColor={"yellow" as const}
        backgroundImage={
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__okaa2)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"none" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            src={{
              src: "/plasmic/nextjs_ableaura_com/images/image2.svg",
              fullWidth: 300,
              fullHeight: 92,
              aspectRatio: 3.257919
            }}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection__kskpv)}
        description={
          "Plasmic's component API gives you complete freedom to attach arbitrary logic and state to build powerful interactive components. Flexibly consume components as a library of presentational components, or directly edit the component’s JSX tree—Plasmic supports multiple codegen schemes with an emphasis on clean code and best practices. "
        }
        header={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.text__dkHZ
            )}
          >
            {"#nocode"}
          </div>
        }
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon__g9M7H)}
            colors={"yellow" as const}
          >
            <Icon10Icon
              className={classNames(defaultcss.all, sty.svg__cNbz6)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={"No-compromise developer control"}
      />

      <ValuePropSection
        backgroundColor={"orange" as const}
        backgroundImage={
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__l4Vb4)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"none" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            src={{
              src: "/plasmic/nextjs_ableaura_com/images/image7.svg",
              fullWidth: 300,
              fullHeight: 145,
              aspectRatio: 2.068966
            }}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection__bY8Zx)}
        description={
          "Continuously sync the latest changes with the code. Plasmic separates presentation from logic so that new changes are easily adopted without conflicts."
        }
        header={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.text__wqzyb
            )}
          >
            {"#nocode"}
          </div>
        }
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon__sg1J6)}
          >
            <Icon6Icon
              className={classNames(defaultcss.all, sty.svg___7215I)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={"Continuously iterate on your UI/UX"}
      />

      <ValuePropSection
        backgroundColor={"orange" as const}
        backgroundImage={
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__czjhq)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"none" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            src={{
              src: "/plasmic/nextjs_ableaura_com/images/image7.svg",
              fullWidth: 300,
              fullHeight: 145,
              aspectRatio: 2.068966
            }}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection__p9K4X)}
        description={
          "Invite and empower your design colleagues to collaborate on the design of the final product. Say goodbye to handoffs altogether, and to divergent sources of truth between design files and code."
        }
        header={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.text__eLc4
            )}
          >
            {"#nocode"}
          </div>
        }
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon__nrsn9)}
          >
            <Icon11Icon
              className={classNames(defaultcss.all, sty.svg__ohP5D)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={"Fix design-engineering collaboration."}
      />

      <ValuePropSection
        backgroundColor={"green" as const}
        backgroundImage={
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__wWmaz)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"none" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            src={{
              src: "/plasmic/nextjs_ableaura_com/images/image7.svg",
              fullWidth: 300,
              fullHeight: 145,
              aspectRatio: 2.068966
            }}
          />
        }
        className={classNames("__wab_instance", sty.valuePropSection__w3R1)}
        description={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.text__luNz7
            )}
          >
            {
              "Check the React components into your git repository. You own everything you make in Plasmic. Want to eject? Walk away any time with plain React code."
            }
          </div>
        }
        header={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.text__ddbCl
            )}
          >
            {"Eject anytime"}
          </div>
        }
        icon={
          <GraphicIcon
            className={classNames("__wab_instance", sty.graphicIcon__uCUej)}
            colors={"green" as const}
          >
            <Icon5Icon
              className={classNames(defaultcss.all, sty.svg__bq1IN)}
              role={"img"}
            />
          </GraphicIcon>
        }
        title={"Zero lock-in"}
      />

      <BottomCtaSection
        data-plasmic-name={"bottomCtaSection"}
        data-plasmic-override={overrides.bottomCtaSection}
        className={classNames("__wab_instance", sty.bottomCtaSection)}
      />

      <Footer
        data-plasmic-name={"footer"}
        data-plasmic-override={overrides.footer}
        className={classNames("__wab_instance", sty.footer)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "pageHero", "bottomCtaSection", "footer"],
  header: ["header"],
  pageHero: ["pageHero"],
  bottomCtaSection: ["bottomCtaSection"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  pageHero: typeof PageHero;
  bottomCtaSection: typeof BottomCtaSection;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPagePrototyping__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPagePrototyping__VariantsArgs;
    args?: PlasmicPagePrototyping__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicPagePrototyping__Fetches;
  } & Omit<PlasmicPagePrototyping__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPagePrototyping__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPagePrototyping__ArgProps,
      internalVariantPropNames: PlasmicPagePrototyping__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicPagePrototyping__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPagePrototyping";
  } else {
    func.displayName = `PlasmicPagePrototyping.${nodeName}`;
  }
  return func;
}

export const PlasmicPagePrototyping = Object.assign(
  // Top-level PlasmicPagePrototyping renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageHero: makeNodeComponent("pageHero"),
    bottomCtaSection: makeNodeComponent("bottomCtaSection"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicPagePrototyping
    internalVariantProps: PlasmicPagePrototyping__VariantProps,
    internalArgProps: PlasmicPagePrototyping__ArgProps
  }
);

export default PlasmicPagePrototyping;
/* prettier-ignore-end */
